name: backend
description: A Dart backend for the Flutter app.
environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  mysql1: ^0.20.0
  shelf_cors_headers: ^0.1.5
  path: ^1.8.3
  dotenv: ^4.1.0
  http: ^1.3.0
